# Default project 

# Import presets
defaults:
  - hydra/job_logging: custom
  - data/sampler: shuffle_sampler
  - train/trainer: default

# MLflow configs
experiment:
  name: Navict

data:
  dataset:
    name: navict
    num_class: 110
    train_val_split: 0.8

# Training configs
train:
  batch_size: 10
  epochs: 10
  save_best_ckpt: True
  num_workers: 2
  ckpt_path: best_ckpt.pth
  eval: False
  optimizer:
    name: adam
    lr: 0.0001
    decay: 0.0001
  criterion:
    # name: cross_entropy
    name: nll_loss
  metric:
    name: classification

# Model configs
model:
  initial_ckpt: 
  name: simple_lstm
  hidden_dim: 100
  num_layers: 1 
  output_size: 110
  embedder:
    name: cbow
    emb_size: 100
    vocab_size: 110 
    initial_ckpt: /workspace/embedding.pth
