# Default project 

# Import presets
defaults:
  - hydra/job_logging: custom
  - data/sampler: shuffle_sampler
  - train/trainer: default

# MLflow configs
experiment:
  name: Navict

data:
  dataset:
    name: navict
    num_class: 110
    train_val_split: 0.8
    len_input: 3

# Training configs
train:
  batch_size: 10
  epochs: 100
  save_best_ckpt: True
  num_workers: 2
  ckpt_path: best_ckpt.pth
  eval: False
  optimizer:
    name: adam
    lr: 0.0001
    decay: 0.0001
  criterion:
    name: cross_entropy
    # name: nll_loss
  metric:
    name: classification

# Model configs
model:
  initial_ckpt: 
  name: simple_nn
  embedder:
    emb_size: 100
    vocab_size: 110 
    initial_ckpt: /workspace/embedder.pth

# model:
#   initial_ckpt: 
#   name: simple_nn
#   emb_size: 100
#   vocab_size: 110 

# model:
#   initial_ckpt: null
#   name: simple_rnn
#   hidden_dim: 100
#   num_layers: 1
#   output_size: 110
#   emb_size: 100
#   vocab_size: 110