# Default project 

# Import presets
defaults:
  - hydra/job_logging: custom
  - data/sampler: shuffle_sampler
  - train/trainer: default

# MLflow configs
experiment:
  name: NavictEmbedder

data:
  dataset:
    name: navict_cbow
    window_size: 3
    num_class: 110

# Training configs
train:
  batch_size: 10
  epochs: 100
  save_best_ckpt: True
  num_workers: 2
  ckpt_path: embedder.pth
  eval: False
  optimizer:
    name: adam
    lr: 0.0001
    decay: 0.0001
  criterion:
    # name: cross_entropy
    name: nll_loss
  metric:
    name: classification

# Model configs
model:
  initial_ckpt: 
  name: cbow_embedder
  vocab_size: 110 
  emb_size: 100
